### ISSUE TITLE
Untextured cell in GDI 10b mission

### ISSUE THREAD

**Issue by Prometheus3375** [CnCNet/ts-patches#100]
It is situated in the right bottom corner.
![image](https://user-images.githubusercontent.com/35541026/226487643-7f2f1796-1b1a-45df-b289-501ed9c72fc5.png)
![image](https://user-images.githubusercontent.com/35541026/226488019-17136a16-90c2-4bfd-ba10-2662a2324540.png)

**Comment by CCHyper** [comment]
@Crimsonum @Bittah Is this a simple fix or is there a bigger issue here?

**Comment by Crimsonum** [comment]
> @Crimsonum @Bittah Is this a simple fix or is there a bigger issue here?

It is a simple fix, the tile is at wrong height level. However, this is not an issue that TS Patches can or should fix, rather the map needs to be fixed in [TS client package](https://github.com/CnCNet/cncnet-ts-client-package).

**Comment by CCHyper** [comment]
@Prometheus3375 Can you please repost this issue on the [TS Client Package](https://github.com/CnCNet/cncnet-ts-client-package) issue tracker, thank you.

Closing this issue.
