### ISSUE TITLE
Devil Tongue  won't Veteran:

### ISSUE THREAD

**Issue by HumbleTS** [CnCNet/ts-patches#15]
Devil Tongue  won't Veteran:

**Comment by HumbleTS** [comment]
Even in firestorm mod where All units have vet. upgrades, they were unable to get tongue to upgrade.

Tried many things, cloning unit, changing particle system, nothing seems to work.

Seems like something is hard coded

**Comment by Rampastring** [comment]
IIRC the damage dealt by the fire stream particle system isn't associated with the unit, so the Devil's Tongue doesn't gain veterancy. Also, the player who uses the DTs doesn't gain kills (for the score screen) when the DT kills things.

**Comment by CCHyper** [comment]
Please report this as a feature request on the Vinifera project tracker so it can be discussed.
https://github.com/Vinifera-Developers/Vinifera/issues
