### ISSUE TITLE
OBS doesn't work anymore

### ISSUE THREAD

**Issue by HumbleTS** [CnCNet/ts-patches#40]
just shows black screen with sound

**Comment by HumbleTS** [comment]
(with automatic rendering)

**Comment by FunkyFr3sh** [comment]
Try game capture instead of monitor capture maybe. Don't think that's anything we can fix, may be better to ask in the OBS forums about it.

It works fine on windows 10 though (both display capture and game capture)

**Comment by HumbleTS** [comment]
Got it working with game capture, ty.
