### ISSUE TITLE
hotkey required to select harvs at all

### ISSUE THREAD

**Issue by HumbleTS** [CnCNet/ts-patches#65]
some sloppy players could benefit from the ability to only be able to select their harvs while holding a hotkey (even if something simple like Ctrl)

this way they cant click-drag their infantry and select a harv on mistake.

**Comment by CCHyper** [comment]
Please report this as a feature request on the Vinifera project tracker so it can be discussed.
https://github.com/Vinifera-Developers/Vinifera/issues
