### ISSUE TITLE
buildbar order always same

### ISSUE THREAD

**Issue by HumbleTS** [CnCNet/ts-patches#71]
even when teching in weird orders.

make buildbar always in same order so its easy to find stuff

**Comment by Rampastring** [comment]
According to the [Arda manual](http://www.stuffhost.de/files/redalert/manual/ArdaManual.html)

`[TechnoType]►CameoOrder= (integer)

The value defines the position in the group (infantry, vehicles, ships, aircraft) this unit will appear in. If two units share the same value, the internal position is used. This feature has to be enabled by the CameoSort option (see above). Larger values are sorted further down. Defaults to -1.`

Supporting the extra key would mean extra work for savegame support (if anyone in our current team knows how to extend saved games, that is). But supporting sorting based on internal position in the game's object type list would be enough.

**Comment by Rampastring** [comment]
Done in https://github.com/CnCNet/ts-patches/commit/22e258e58024d41bd4eff6919701db510032dc3e

dkeeton / Funky can enable this for CnCNet TS if they wish to.
