### ISSUE TITLE
"No CD" option doesn't seem to work or lacks documentation.

### ISSUE THREAD

**Issue by daf0x** [CnCNet/ts-patches#80]
Problem: When starting a (Firestorm) campaign, there appears an error message "unable to read scenario".

Here's what I did (a fresh install, specifically to test this problem):
1. Install Tiberian Sun from original CD (Windows 10, using Windows 98 compatibility mode)
1. Install Firestorm expansion from original CD (Windows 10, using Windows 98 compatibility mode)
1. Copy over all the files mentioned [here](https://cncnz.com/features/technical-support-help-guides/installing-command-conquer-tiberian-sun-firestorm/). 
 Note: did not rename `movies03.mix` to `expand03.mix` at this point.
 Note: did not overwrite any existing files at this point.
1. Install the 2.03 official patch (there was a weird "Missing or Invalid Registry/INI entry" error, after which (eventually) a "Select file" dialog pops up, but after pointing it to `SUN.EXE` the patch installed without problems.
1. Install [TSpatch](https://forums.cncnet.org/topic/2606-tiberian-sun-patches-fix-for-the-windows-8-10-menu-problems-and-more/)
1. Run the game.
 Note: In the TSpatch settings, at this point the "No CD" option was automatically enabled.
 Note: Noticed that when selecting the Firestorm emblem, the movie does not play. It does play for regular Tiberian Sun.
 Note: I do not have, nor did I install, any "The First Decade Patch".
1. Exit out of game
1. Rename `movies03.mix` to `expand03.mix`
1. Run the game
 Note: Now when selecting the Firestorm emblem the movie plays correctly.
 Note: Starting a campaign still says "unable to read scenario"

I'm guessing there is another file that needs to be renamed or something, but I can't find what file or what name. I do see lots and lots of people having the same problem online, but nobody seems to have been able to get Firestorm to work with the "No CD" option, or at least there is never a conclusion to any of the forum threads. There is a lot of mentioning that it should work with the original CDs (but not The First Decade). However, for me this doesn't seem to work.

--- update

It seems that renaming `maps03.mix` to `expand04.mix` fixes Firestorm, which now seems to work correctly; I can start a new campaign, the movies play, loading the next mission (from a end-of-level save) seems to work.
However, I've now noticed that the *intro* movies for the regular Tiberian Sun campaing don't seem to play either. The strange thing is that the missions do load, and inter-mission movies *do* seem to play, so it's just the opening cinematic that doesn't seem to work.

**Comment by tore29** [comment]
The problem here is that Funky's TS patch uses an exe meant for the First Decade and The Ultimate Collection and the description on that page is meant for a no CD install of the CD version.

The TFD noCD exe doesn't read on disk Firestorm filenames correctly. As in TFD movies03.mix contents are in movies01.mix and the Firestorm missions are scattered around in the root folder of the game. (fsgdi**.mix and fsnod**.mix)

**Comment by daf0x** [comment]
I think you are correct. I've been playing around with the mix files, using "XCC MIX Editor" and "fix_tfd_ts_vids", and I've gotten to something that appears to be working. I've attached my "patch" for the .mix files below.

The procedure I followed for creating these patches is as follows:
- Open .mix file in "XCC MIX Editor"
- Disable encryption
- Save file
- Edit file to strip XCC 'local mix database' (strip trailer and adjust file size in header)
- 'move' the 'local mix database' entry in the header to the end of the header
- fill the 'local mix database' entry with 'ff'
- Use "fix_tfd_ts_vids.exe u" to change the 'intro.vqa' to 'intr{0,1}.vqa'
  This step seemed required to get Tiberian Sun to recognize the movies,
  this might have to do with the 'sorting' it does?

The only strange this is that XCC MIX Editor adds this 'local mix database' file, but I don't see where it is allocating the space for this entry from as it does not change the file size. I'm slightly worried that a different movie file might now be 'missing'.

Combining these patches with the "rename `movies03.mix` to `expand03.mix`", I now _appear_ to have a working NoCD for the original disc release + TSpatch. If this is indeed the case, TSpatch might be able to do the same thing if it detects an original disc release duing installation; replace the headers of the two `movies0{1,2}.mix` files and rename `movies03.mix`.

---

<details>
<summary>MOVIES01.MIX.xdelta3</summary>

```
begin-base64 644 -
1sPEAAQgTU9WSUVTMDEuTUlYLy9NT1ZJRVMwMS5vcmlnLk1JWC8Fg//7foQC
hBKEgIAAAIN3DQEg4G2OAAAAACoAGoI0Hb/9bINas+MG2samADjibIqqlnIC
HgpPAylp8YxqDVoTCJ/VACs6bplKAAAA9HVcAJzfm536pskAZJpAAAfNaZ46
eooHwnimAGTehJ5KdlwAsDBtABpQO6Bq6bQZtmEaANvynKqKrZoaliVUABQy
VauK7VsC4uoHADpJmq36HkQbVlNYACVwQrG6ERgWtEkTAwUv2bH6mb8VuHdY
APYW9LnamiwbHoQXACLIOcFqhVkQ4AMeAQ/pMsJacpwbygjAAJfYKc/ajgAa
iiJcACqKQ9Aqe1wcAtskAAxsodNaM/sJ0mwiAfkKYNT6XnIV+jpNANkxI+Qq
iOwc8PlHAHKUQuQ6VoEc6DFrAGk1cOk6jWkCbAkJAHwNq+k6JG4NjHT0ACPF
APFqQQoBOnGEAOJ8BvQq0+4asMc9AP+O6OEHWkxED6y4kADGvNwNqrKOAdI6
zQA+eKQVKkvPGaxDMQCpv/0YOqAdC/KDUAK+daMleqwvFGa+VwD3Ndolethj
ArS0BQDrx9Qu6mqHFIi/ugA68OwxelsrGeiNiQAfBYE6CgXVD2CAhAB04As+
eipCFXg0MABekkFAyphiDpCz4QAaLjBIyqDBBY4SIgHVT2VNarFcGhz8PQCi
HjVVCvMwCEhAygEAV9NoSol3ESCE4gEBgkIADAGBNBOD//t+AAWEgIAAhICA
ABKEgIAAAAAFATJdK7IThICAAAAFhICAAIiAgAAShICAAAAABQG8XPFME4SA
gAAABYSAgACMgIAAEoSAgAAAAAUBilTn7xOEgIAAAAWEgIAAkICAABKEgIAA
AAAFAcBp7QcThICAAAAFhICAAJSAgAAShICAAAAABQH2CKpQE4SAgAAABYSA
gACYgIAAEoSAgAAAAAUB4Sh8EhOEgIAAAAWEgIAAnICAABKEgIAAAAAFASMg
kHYThICAAAAFhICAAKCAgAAShICAAAAABQHkKYucE4SAgAAABYSAgACkgIAA
EoSAgAAAAAUBEsJu+xOEgIAAAAWEgIAAqICAABKEgIAAAAAFAffZ/9wThICA
AAAFhICAAKyAgAAShICAAAAABQEAvrMtE4SAgAAABYSAgACwgIAAEoSAgAAA
AAUBPAlNohOEgIAAAAWEgIAAtICAABKEgIAAAAAFAalVdAkThICAAAAFhICA
ALiAgAAShICAAAAABQE2hUNwE4SAgAAABYSAgAC8gIAAEoSAgAAAAAUB280O
XROEgIAAAAWEgIAAwICAABKEgIAAAAAFAUBI8tcThICAAAAFhICAAMSAgAAS
hICAAAAABQFlSwARE4SAgAAABYSAgADIgIAAEoSAgAAAAAUB1+Pq+hOEgIAA
AAWEgIAAzICAABKEgIAAAAAFAbZkb3kThICAAAAFhICAANCAgAAShICAAAAA
BQHDjVRYE4SAgAAABYSAgADUgIAAEoSAgAAAAAUB7XPuaROEgIAAAAWEgIAA
2ICAABKEgIAAAAAFAdDG5xYThICAAAAFhICAANyAgAAShICAAAAABQGzBa6j
E4SAgAAABYSAgADggIAAEoSAgAAAAAUBqAAiKBOEgIAAAAWEgIAA5ICAABKE
gIAAAAAFAYWKxQEThICAAAAFhICAAOiAgAAShICAAAAABQFzlmhfE4SAgAAA
BYSAgADsgIAAEoSAgAAAAAUBxj8UchOEgIAAAAWEgIAA8ICAABKEgIAAAAAF
AcheoE4ThICAAAAFhICAAPSAgAAShICAAAAABQEZAh8TE4SAgAAABYSAgAD4
gIAAEoSAgAAAAAUBhJ0UBhOEgIAAAAWEgIAA/ICAABKEgIAAAAAFATs6vZUT
hICAAAAFhICAAIGAgIAAEoSAgAAAAAUBwL+GHROEgIAAAAWEgIAAgYSAgAAS
hICAAAAABQEycOknE4SAgAAABYSAgACBiICAABKEgIAAAAAFAZ36Zl0ThICA
AAAFhICAAIGMgIAAEoSAgAAAAAUBqtvxmROEgIAAAAWEgIAAgZCAgAAShICA
AAAABQF7aN7zE4SAgAAABYSAgACBlICAABKEgIAAAAAFASUfNjkThICAAAAF
hICAAIGYgIAAEoSAgAAAAAUBzaKHTBOEgIAAAAWEgIAAgZyAgAAShICAAAAA
BQF+DvRCE4SAgAAABYSAgACBoICAABKEgIAAAAAFAeeQzjYThICAAAAFhICA
AIGkgIAAEoSAgAAAAAUB4WralBOEgIAAAAWEgIAAgaiAgAAShICAAAAABQFN
YH8KE4SAgAAABYSAgACBrICAABKEgIAAAAAFAUuWIsYThICAAAAFhICAAIGw
gIAAEoSAgAAAAAUBrecNUROEgIAAAAWEgIAAgbSAgAAShICAAAAABQFQOqel
E4SAgAAABYSAgACBuICAABKEgIAAAAAFAZkVhMgThICAAAAFhICAAIG8gIAA
EoSAgAAAAAUBOOpkNxOEgIAAAAWEgIAAgcCAgAAShICAAAAABQFmYzB1E4SA
gAAABYSAgACBxICAABKEgIAAAAAFAT+O5GYThICAAAAFhICAAIHIgIAAEoSA
gAAAAAUBbDozBROEgIAAAAWEgIAAgcyAgAAShICAAAAABQG0GOx6E4SAgAAA
BYSAgACB0ICAABKEgIAAAAAFAd/Ih94ThICAAAAFhICAAIHUgIAAEoSAgAAA
AAUBkG37WBOEgIAAAAWEgIAAgdiAgAAShICAAAAABQEbliEuE4SAgAAABYSA
gACB3ICAABKEgIAAAAAFAWSrLkAThICAAAAFhICAAIHggIAAEoSAgAAAAAUB
LwDehROEgIAAAAWEgIAAgeSAgAAShICAAAAABQGk4ciGE4SAgAAABYHSiByB
6ICAABKB0ogcAAAFARNrvMkTgdKIHAA=
====
```
</details>

<details>
<summary>MOVIES02.MIX.xdelta3</summary>

```
begin-base64 644 -
1sPEAAQgTU9WSUVTMDIuTUlYLy9NT1ZJRVMwMi5vcmlnLk1JWC8Fg//8OoNG
g1WEgIAAAIM2EAJTd2O0AAAAACUAttA+HWla15gGxpcT7l2cAZzfm53G5lIA
ZJpAABpQO6A2jdoFtmEaABk73aImHwAW8vjdAbai5qQ2gZMAYqa+AMsTMaUG
nikZrjHhAYn2C7d2K8A3I429JsYxBvhXQwJd1BrBJh51CGy85gMP6TLC1uxZ
HMoIwADayxrIlj4ADmZxngCX2CnPts8KG4oiXAAqikPQpvUZHQLbJABi+x/V
BrCeDvi/ugPTTwfZRgAAAHbmUgBxBCPgpjImBkCvBADZMSPkRvJmG/D5RwBy
lELkhvlUBegxawDAsvno5kBIGL5OOgDifAb0NuyuG7DHPQD/fxhGA5baWwwA
ZKQBxrzcDaYnUgHSOs0APnikFfbu9AWsQzEA0uDTGHbfMQK4LxEAxyhDHgZw
WRL+VT4BLY+XIDYPQwJihEAAZWGlI6aPghhUDqcA/SLJLSbIswI8RgsAdOAL
PqaTgwJ4NDAAzImLU/YjNBUm+8sAW07SXoZiHwLofBIAvOiBaSYY3heyKGoA
BaombSbF7ARaNGgAkgOsbubhKgY85AYA1C/je+az7BvsOG0Au3DofWYOvwK0
ti0CAVklAYEcAAwBgUATg//8OjAABYSAgACEgIAAEoSAgAAAAAUB8FCQPBOE
gIAAAAWEgIAAiICAABKEgIAAAAAFAfHJ3WIThICAAAAFhICAAIyAgAAShICA
AAAABQGqB4gZE4SAgAAABYSAgACQgIAAEoSAgAAAAAUBwtuhdxOEgIAAAAWE
gIAAlICAABKEgIAAAAAFAdUoBPsThICAAAAFhICAAJiAgAAShICAAAAABQGs
CQE4E4SAgAAABYSAgACcgIAAEoSAgAAAAAUBZBK/gxOEgIAAAAWEgIAAoICA
ABKEgIAAAAAFAShV11QThICAAAAFhICAAKSAgAAShICAAAAABQF9sAngE4SA
gAAABYSAgACogIAAEoSAgAAAAAUBfIPSwBOEgIAAAAWEgIAArICAABKEgIAA
AAAFAS5np1oThICAAAAFhICAALCAgAAShICAAAAABQGo6y8fE4SAgAAABYSA
gAC0gIAAEoSAgAAAAAUBXZesYROEgIAAAAWEgIAAuICAABKEgIAAAAAFAbfU
LjgThICAAAAFhICAALyAgAAShICAAAAABQEQe9FGE4SAgAAABYSAgADAgIAA
EoSAgAAAAAUBm8jNnROEgIAAAAWEgIAAxICAABKEgIAAAAAFAZKwTD4ThICA
AAAFhICAAMiAgAAShICAAAAABQGXXBLZE4SAgAAABYSAgADMgIAAEoSAgAAA
AAUBEQhhyxOEgIAAAAWEgIAA0ICAABKEgIAAAAAFAZUp2JoThICAAAAFhICA
ANSAgAAShICAAAAABQELKzLKE4SAgAAABYSAgADYgIAAEoSAgAAAAAUBA5Bl
oBOEgIAAAAWEgIAA3ICAABKEgIAAAAAFAXu7jH4ThICAAAAFhICAAOCAgAAS
hICAAAAABQE+EIsyE4SAgAAABYSAgADkgIAAEoSAgAAAAAUBOAAfghOEgIAA
AAWEgIAA6ICAABKEgIAAAAAFAXkTzF4ThICAAAAFhICAAOyAgAAShICAAAAA
BQG8tuRbE4SAgAAABYSAgADwgIAAEoSAgAAAAAUBga4BRROEgIAAAAWEgIAA
9ICAABKEgIAAAAAFAbcxuYEThICAAAAFhICAAPiAgAAShICAAAAABQFrZorK
E4SAgAAABYSAgAD8gIAAEoSAgAAAAAUBe/jf7BOEgIAAAAWEgIAAgYCAgAAS
hICAAAAABQEj0DJ9E4SAgAAABYSAgACBhICAABKEgIAAAAAFASZLrDoThICA
AAAFhICAAIGIgIAAEoSAgAAAAAUBJH+J6xOEgIAAAAWEgIAAgYyAgAAShICA
AAAABQGi1js1E4SAgAAABYSAgACBkICAABKEgIAAAAAFAZpzC7oThICAAAAF
hICAAIGUgIAAEoSAgAAAAAUBbvMxRROEgIAAAAWEgIAAgZiAgAAShICAAAAA
BQGEA74QE4SAgAAABYSAgACBnICAABKEgIAAAAAFAcB7I/UThICAAAAFhICA
AIGggIAAEoSAgAAAAAUBKpsyaROEgIAAAAWEgIAAgaSAgAAShICAAAAABQF4
/GeSE4SAgAAABYSAgACBqICAABKEgIAAAAAFARFAsfwThICAAAAFhICAAIGs
gIAAEoSAgAAAAAUB50iXbxOEgIAAAAWEgIAAgbCAgAAShICAAAAABQEorMHA
E4SAgAAABYSAgACBtICAABKEgIAAAAAFATAg6WEThICAAAAFhICAAIG4gIAA
EoSAgAAAAAUBD+rsohOEgIAAAAWEgIAAgbyAgAAShICAAAAABQH/seEsE4SA
gAAABYSAgACBwICAABKEgIAAAAAFAXQRmi0ThICAAAAFhICAAIHEgIAAEoSA
gAAAAAUBF5DhxhOEgIAAAAWEgIAAgciAgAAShICAAAAABQH3RwJyE4SAgAAA
BYSAgACBzICAABKEgIAAAAAFAejdZTkThICAAAAFhICAAIHQgIAAEoSAgAAA
AAUBtFVjNhOEgIAAAAWEgIAAgdSAgAAShICAAAAABQFamgn2E4SAgAAABYSA
gACB2ICAABKEgIAAAAAFAXbob3EThICAAAAFhICAAIHcgIAAEoSAgAAAAAUB
Ci4/5hOEgIAAAAWEgIAAgeCAgAAShICAAAAABQEF3kHQE4SAgAAABYSAgACB
5ICAABKEgIAAAAAFARNaT5kThICAAAAFgfukfIHogIAAEoH7pHwAAAUBuMJO
kBOB+6R8AA==
====
```
</details>

**Comment by daf0x** [comment]
Just a may-be related FYI:

I ran into a crash at the end of Firestorm mission 6 ("Escape from Cabal"). I traced this back to missing Nyerguds' Firestorm videos add-on, which installs these files:
* `maps03.mix`
* `expand02.mix`
* `artfs.ini`

Note that because we renamed `maps03.mix` to `expand03.mix` there should be no file conflicts.

I was able to trace this by comparing my new install to an older install, where this mission did complete successfully. However, I do not know if it is essential that these files are installed, because I resumed this mission from a save file from the older install, where this fix was already present. I.e. it is possible that without "fs_videos_update.rar" the mission may still complete fine if it is started from a clean install; I don't know what happens with save games work if the installation is modified.

**Comment by daf0x** [comment]
One more comment :)

I was going over the list of `.mix` files one more time, and I don't think the the list of files mentioned on the [installation guide](https://cncnz.com/features/technical-support-help-guides/installing-command-conquer-tiberian-sun-firestorm/) is correct for the "I have the retail CD version." option.

<details>
<summary>Presently, this is the list of files the guide suggests.</summary>

* **Tiberian Sun GDI disc**
  maps01.mix,
  movies01.mix,
  multi.mix (except if you install Firestorm),
  scores.mix,
  sidecd01.mix,
  TS1.dsk.
* **Tiberian Sun Nod disc**
  maps02.mix,
  movies02.mix,
  sidecd02.mix,
  TS2.dsk.
* **Tiberian Sun Firestorm disc**
  e01scd01.mix,
  e01scd02.mix,
  maps03.mix,
  movies03.mix (you need to rename this to something like expand03.mix),
  multi.mix (overwrite the one from vanilla Tiberian Sun),
  scores01.mix,
  TS3.dsk.

</details>

However, the `sidecd01.mix`, `sidecd02.mix`, and `scores.mix` files are different on the Firestorm disc from the GDI/NOD disc. This might mean that there is missing Firestorm content or other problems if these are taken from the base game and playing the Firestorm campaign.

<details>
<summary>I suggest to copy this list of files instead.</summary>

* **Tiberian Sun GDI disc**
  TS1.dsk,
  maps01.mix,
  movies01.mix,
  sidecd01.mix (except if you install Firestorm),
  scores.mix (except if you install Firestorm),
  multi.mix (except if you install Firestorm).

* **Tiberian Sun Nod disc**
  TS2.dsk,
  maps02.mix,
  movies02.mix,
  sidecd02.mix (except if you install Firestorm).

* **Tiberian Sun Firestorm disc**
  TS3.dsk,
  maps03.mix (rename this to expand03.mix),
  movies03.mix (rename this to expand04.mix),
  e01scd01.mix,
  e01scd02.mix,
  scores.mix,
  scores01.mix,
  sidecd01.mix,
  sidecd02.mix,
  Install\multi.mix.

</details>

By renaming the `maps03.mix` and `movies03.mix` files to `expand03.mix` and `expand04.mix` respectively, there will be a gap free for `expand02.mix`, Nyerguds' Firestorm-videos add on can slot in without file conflicts.

**Comment by CCHyper** [comment]
@Crimsonum @Bittah Is this still the case with the current ts-patches setup?

**Comment by Crimsonum** [comment]
Is there point in supporting the CD release anymore? The freeware release works out-of-the-box and comes with Firestorm included. There's nothing to gain from the CDs AFAIK.

**Comment by CCHyper** [comment]
> Is there point in supporting the CD release anymore? The freeware release works out-of-the-box and comes with Firestorm included. There's nothing to gain from the CDs AFAIK.

Valid point, I'll close this issue.
